# Admin Stuffs

In [1]:
# You would need to install python 3 + Jupyter notebook
# Easiest way is to install via anaconda
# You would also need the following packages
1. Pandas
2. sklearn
3. numpy

# Basic

## Data Types and Variables

In [37]:
# A variable holds a value that may change.
a = 1

In [38]:
a # integer

1

In [40]:
# Can also do float
a = 1.0
a

1.0

In [42]:
# String can be double quote or single quote
b = 'hello'
c = "hello"

In [43]:
b, c

('hello', 'hello')

In [44]:
# Boolean (True / False)
d = True
e = False

In [45]:
d

True

In [49]:
not d

False

## List and Dictionary

In [57]:
# a list hold a series of items
e = [1, 2, 3]

In [58]:
# You can add items to it
[1,2,3] + [4]

[1, 2, 3, 4]

In [59]:
e[0]

1

In [60]:
# a tuple can be thought of a list with fixed length
f = (1, 2, 3)

In [62]:
f[0]

1

In [61]:
# a dictionary is a named list 
g = {
    'fruit': 'apple',
    'price': 10
}

In [63]:
g['fruit']

'apple'

# Vectorized Arithmetrics

In [64]:
import numpy as np

In [86]:
type([1,2,3,4])

list

In [87]:
a = np.array([1,2,3,4])

In [85]:
type(a)

numpy.ndarray

In [81]:
a

array([1, 2, 3, 4])

In [68]:
a + 1

array([2, 3, 4, 5])

In [75]:
a - 1

array([0, 1, 2, 3])

In [69]:
a * 2

array([2, 4, 6, 8])

In [70]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [71]:
a ** 2

array([ 1,  4,  9, 16])

In [74]:
a % 2 

array([1, 0, 1, 0])

In [77]:
# Useful functions in the numpy libraries
np.mean(a)

2.5

In [78]:
np.sum(a)

10

# Lots of other useful function, consult numpy documentations
https://docs.scipy.org/doc/

In [79]:
# built-in documentations available with ?
?np.mean

# Getting Started

In [4]:
import pandas as pd

In [6]:
# Read data
iris = pd.read_csv("iris.csv")

In [7]:
# Dataframe
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

In [8]:
# Getting a Series from a DataFrame
iris['Sepal.Length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal.Length, Length: 150, dtype: float64

In [17]:
# A Dataframe consists of columns of Series

df = pd.DataFrame({
    'number': pd.Series([1,2,3,4]),
    'purchased': pd.Series([True, True, False, False]), 
    'product': pd.Series(["Apple", "Orange", "Banana", "Strawberry"])
})
df

number  purchased     product
0       1       True       Apple
1       2       True      Orange
2       3      False      Banana
3       4      False  Strawberry

In [20]:
df.iloc[0,0]

1

In [21]:
df.iloc[:, 1]

0     True
1     True
2    False
3    False
Name: purchased, dtype: bool

In [22]:
df.iloc[0,:]

number           1
purchased     True
product      Apple
Name: 0, dtype: object

In [23]:
df.iloc[3,2]

'Strawberry'

In [ ]:
# Other Data Manipulation

In [24]:
df.shape

(4, 3)

In [25]:
df.columns

Index(['number', 'purchased', 'product'], dtype='object')

In [26]:
df.head()

number  purchased     product
0       1       True       Apple
1       2       True      Orange
2       3      False      Banana
3       4      False  Strawberry

In [31]:
a = df['number']
a

0    1
1    2
2    3
3    4
Name: number, dtype: int64

In [32]:
a.mean()

2.5

In [33]:
?a.mean

# Function

In [88]:
def add(x, y):
    return x+y

In [90]:
add(1, 2)

3

# Exercise

In [92]:
df = pd.DataFrame({
    'number': pd.Series([1,2,3,4]),
    'purchased': pd.Series([True, True, False, False]), 
    'product': pd.Series(["Apple", "Orange", "Banana", "Strawberry"])
})
df

number  purchased     product
0       1       True       Apple
1       2       True      Orange
2       3      False      Banana
3       4      False  Strawberry

In [ ]:
# Extract the name Banana using iloc
df.iloc[ ? , ?]

In [ ]:
# Extract the column "product" using iloc
df.iloc[?, ?]

In [ ]:
# Extract the column "product" using the column name
df[?]

In [ ]:
# BONUS: how to get the sum of "number"?
df[?].?